# Generated by Django 4.2.13 on 2024-07-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pizzas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topping",
            name="pizza",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pizzas.pizza",
            ),
        ),
    ]
