# Generated by Django 4.2.13 on 2024-07-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizzas", "0002_topping_pizza"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
