# Generated by Django 4.2.13 on 2024-07-07 21:44

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("pizzas", "0005_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default="fallback_image.jpg",
                force_format="JPEG",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[750, 500],
                upload_to="pizza_images/",
            ),
        ),
    ]
